name: SonarQube

on:
  push:
    branches:
      - develop

jobs:
  sonar:
    runs-on: ubuntu-latest

    # LE DECIMOS A GITHUB QUE TRABAJE DENTRO DE LA CARPETA SESIÓN 8
    defaults:
      run:
        working-directory: "Sesion 8"

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          sparse-checkout: .  # Mantiene el checkout simple

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=ucv_ate_si_laboratorios
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}